/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _UP_DOWN_H_RPCGEN
#define _UP_DOWN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct chunk {
	char sendBuff[1025];
	char dirname[1000];
	int flag;
};
typedef struct chunk chunk;

#define UPDOWN 0x2fffffff
#define UPDOWN_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define UD 1
extern  struct chunk * ud_1(chunk *, CLIENT *);
extern  struct chunk * ud_1_svc(chunk *, struct svc_req *);
extern int updown_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define UD 1
extern  struct chunk * ud_1();
extern  struct chunk * ud_1_svc();
extern int updown_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_chunk (XDR *, chunk*);

#else /* K&R C */
extern bool_t xdr_chunk ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_UP_DOWN_H_RPCGEN */
